# Generated by Django 6.0.2 on 2026-03-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='desctiption',
            new_name='description',
        ),
    ]
